# Use container based architecture for caching
sudo: false
language: node_js
node_js:
    - "node"
    - 6
    - 4
install:
    - npm update
script: npm run build && npm run test
after_success: npm run coverage
cache:
    directories:
        - node_modules/
